### ISSUE TITLE
Plotting frequency while the plot axis is called population size

### ISSUE THREAD

**Issue by loukesio** [MathOnco/EvoFreq#11]
Dear developer(s),

The package is very cool. I have n issue to point.  In your package, you calculate the frequency of each clone per time but at the end, the y-axis to the plot refers to the population size.
That might be misleading. 

What someone needs to do is to scale it from 0 to 1 and then cut in the middle with a horizontal line.  The same problem someone sees to ggmuler as well.

Thank you so much for the great effort you have done.

**Comment by rschenck** [comment]
Thanks for your comments @loukesio, I think this warrants a larger discussion. Give me a little bit to formulate my thoughts on this.

**Comment by rschenck** [comment]
http://ryanoschenck.com/2019/09/10/on-the-interpretability-and-users-of-a-muller-plot/ have a look here. I generally agree with you. I believe you can do some of what you're suggesting by setting an option within EvoFreq. Population Size is correct for some users, but not all. It will depend on what data is fed to EvoFreq. I will leave this open for now as it's a discussion that we have had before and maybe it will lead to a consensus.

**Comment by loukesio** [comment]
@rschenck thanks for the prompt reply. 
I have another question to ask. I do not think it is worth it to open an issue for it.

Do you have somewhere the file "run_name.summ.json"
I want to use a dendrogram for simulated data that has not been processed by PhyloWGS. 

I mean if I know how the "run_name.summ.json" looks like I can simulate it. For now, I am getting the following error. 

Error in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") :
  cannot open file 'run_name.summ.json': No such file or directory

**Comment by cdgatenbee** [comment]
Hi @loukesio, could you please clarify what you mean by "simulated data"? If the results are from a computer simulation, and you have population sizes in a csv or tab delimited file, then that is all you need :) No need to process it through PhyloWGS unless it actually sequence data. 

Also, regarding plotting frequencies, there is an option to plot the actual frequencies (instead of population sizes) that scales everything between 0 and 1 at each timepoint, which can be done by setting scale_by_sizes_at_time = T in the get_evofreq() function. Is this what you mean? There is still the issue that estimating exact frequencies or population sizes from the y-axis is a little tricky, but I agree with @rschenck  that this is somewhat inherent to Muller plots, and maybe stacked plots in general? But they still provide a good picture of the evolutionary dynamics, so I think they are still a useful visualization tool.

Hope that helps, but if not let me know.
